name       : fio
version    : '2.20'
release    : 3
source     :
    - https://github.com/axboe/fio/archive/fio-2.20.tar.gz : eb51fbad161929f1bcd6c1d0d09d2c7543651f834aec860ba5def9bc52dcc3ae
license    : GPL-2.0
component  : programming.tools
summary    : Thread/Process tool
description: |
    fio is a tool that will spawn a number of threads or processes doing a particular type of io action as specified by the user. fio takes a number of global parameters, each inherited by the thread unless otherwise parameters given to them overriding that setting is given. The typical use of fio is to write a job file matching the io load one wants to simulate.
builddeps  :
    - pkgconfig(gdk-2.0)
setup      : |
    ./configure --prefix=/usr --enable-gfio
build      : |
    %make
install    : |
    %make_install
