name       : fio
version    : '3.6'
release    : 5
source     :
    - https://github.com/axboe/fio/archive/fio-3.6.tar.gz : 184982f5cdddada40b08b3d9a82f4de5e698374d9bfdfb7c85d10e9fddf51b8c
license    : GPL-2.0
component  : programming.tools
summary    : Thread/Process tool
description: |
    fio is a tool that will spawn a number of threads or processes doing a particular type of io action as specified by the user. fio takes a number of global parameters, each inherited by the thread unless otherwise parameters given to them overriding that setting is given. The typical use of fio is to write a job file matching the io load one wants to simulate.
builddeps  :
    - pkgconfig(gdk-2.0)
setup      : |
    ./configure --prefix=/usr \
                --extra-cflags="$CFLAGS" \
                --enable-gfio
build      : |
    %make
install    : |
    %make_install
