name       : fio
version    : '3.35'
release    : 15
source     :
    - https://github.com/axboe/fio/archive/refs/tags/fio-3.35.tar.gz : 36b98f35622ee594364bfd9a527523a44cda0dda2455ba9f2dcae2cd7dd3859f
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Thread/Process tool
description: |
    fio is a tool that will spawn a number of threads or processes doing a particular type of io action as specified by the user. fio takes a number of global parameters, each inherited by the thread unless otherwise parameters given to them overriding that setting is given. The typical use of fio is to write a job file matching the io load one wants to simulate.
builddeps  :
    - pkgconfig(gdk-2.0)
    - libaio-devel
setup      : |
    ./configure --prefix=/usr \
                --extra-cflags="$CFLAGS" \
                --enable-gfio
build      : |
    %make
install    : |
    %make_install
